### ISSUE TITLE
Allow groups to be conditionally collapsible with `->collapsible()`

### ISSUE THREAD

**Issue by binaryfire** [KanuniLab/filament-cards#2]
Would it be possible to add a `->collabsible()` method to groups? I'd like to group items on my settings pages but not allow them to be collapsed / expanded (i.e. keep them permanantly expanded and hide the collapse arrow). Core uses `->collapsible()` for the sidebar so it keeps the fluent methods consistent.

**Comment by tjodalv** [comment]
Can you elaborate a bit more why that feature would be useful and what is your use-case? If it make sense maybe I could add it in the next update.

**Comment by tjodalv** [comment]
I've added this option in the latest version v0.2 and documented the feature here:

https://github.com/KanuniLab/filament-cards/tree/main?tab=readme-ov-file#prevent-groups-from-collapsing

**Comment by binaryfire** [comment]
@tjodalv Wow, that was fast. Nice!

It's just a UI/UX preference thing. Most card-style settings pages don't have a collapse option (see some example screenshots below). 

Personally I think it gets in the way more than it helps. Users end up collapsing some things, then get confused when they can't find something (because they've forgotten what they collapsed). Users with poor vision can also accidentally collapse things when clicking in the wrong area. By comparison, having all the cards there and doing a little scrolling to find what they want is a simpler, more intuitive experience. But that's just my opinion :)

![image](https://github.com/user-attachments/assets/342bf4aa-0d9f-4b34-bd95-ee6720899efd)
![image](https://github.com/user-attachments/assets/3b21e9c0-9544-4fbf-a158-6b9b418fcaab)

**Comment by tjodalv** [comment]
It wasn't too difficult to implement this feature, so I added it immediately since I needed to update the documentation as well. By the way, which plugin is shown in the screenshot? Is your custom page or a plugin?

**Comment by binaryfire** [comment]
@tjodalv Great :) Regarding the screenshots: they're just images I found when I Googled settings pages examples. I've been using clusters for my Filament settings pages.
